import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";
import Bottombar from "@/components/shared/Bottombar";
import "../globals.css";
import getDataFromToken from "@/lib/helpers/getDataFromToken";
import AuthProvider from "@/provider/AuthProvider";
import { useAuth } from "@/lib/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getDataFromToken();

  useAuth.setState({ id: user?.id });

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-dark-1
      `}
      >
        <AuthProvider id={user?.id} />
        <Topbar />
        <main className="flex flex-row">
          <LeftSidebar />
          <section className="main-container">
            <div className="w-full max-w-4xl">{children}</div>
          </section>
          {/* <RightSidebar /> */}
        </main>
        <Bottombar />
      </body>
    </html>
  );
}
